// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: cexPriceUpdate.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CexPriceUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price       string  `protobuf:"bytes,1,opt,name=Price,proto3" json:"Price,omitempty"`
	BaseVolume  float64 `protobuf:"fixed64,2,opt,name=BaseVolume,proto3" json:"BaseVolume,omitempty"`
	QuoteVolume float64 `protobuf:"fixed64,3,opt,name=QuoteVolume,proto3" json:"QuoteVolume,omitempty"`
}

func (x *CexPriceUpdate) Reset() {
	*x = CexPriceUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cexPriceUpdate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CexPriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CexPriceUpdate) ProtoMessage() {}

func (x *CexPriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cexPriceUpdate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CexPriceUpdate.ProtoReflect.Descriptor instead.
func (*CexPriceUpdate) Descriptor() ([]byte, []int) {
	return file_cexPriceUpdate_proto_rawDescGZIP(), []int{0}
}

func (x *CexPriceUpdate) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CexPriceUpdate) GetBaseVolume() float64 {
	if x != nil {
		return x.BaseVolume
	}
	return 0
}

func (x *CexPriceUpdate) GetQuoteVolume() float64 {
	if x != nil {
		return x.QuoteVolume
	}
	return 0
}

var File_cexPriceUpdate_proto protoreflect.FileDescriptor

var file_cexPriceUpdate_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x65, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x68,
	0x0a, 0x0e, 0x43, 0x65, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x61, 0x73, 0x65, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x42, 0x61, 0x73, 0x65,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x6b, 0x67,
	0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cexPriceUpdate_proto_rawDescOnce sync.Once
	file_cexPriceUpdate_proto_rawDescData = file_cexPriceUpdate_proto_rawDesc
)

func file_cexPriceUpdate_proto_rawDescGZIP() []byte {
	file_cexPriceUpdate_proto_rawDescOnce.Do(func() {
		file_cexPriceUpdate_proto_rawDescData = protoimpl.X.CompressGZIP(file_cexPriceUpdate_proto_rawDescData)
	})
	return file_cexPriceUpdate_proto_rawDescData
}

var file_cexPriceUpdate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cexPriceUpdate_proto_goTypes = []interface{}{
	(*CexPriceUpdate)(nil), // 0: binary.CexPriceUpdate
}
var file_cexPriceUpdate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cexPriceUpdate_proto_init() }
func file_cexPriceUpdate_proto_init() {
	if File_cexPriceUpdate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cexPriceUpdate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CexPriceUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cexPriceUpdate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cexPriceUpdate_proto_goTypes,
		DependencyIndexes: file_cexPriceUpdate_proto_depIdxs,
		MessageInfos:      file_cexPriceUpdate_proto_msgTypes,
	}.Build()
	File_cexPriceUpdate_proto = out.File
	file_cexPriceUpdate_proto_rawDesc = nil
	file_cexPriceUpdate_proto_goTypes = nil
	file_cexPriceUpdate_proto_depIdxs = nil
}
