// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: dexeEvents.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DexeEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number       []byte         `protobuf:"bytes,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Timestamp    int64          `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Network      string         `protobuf:"bytes,3,opt,name=Network,proto3" json:"Network,omitempty"`
	CustomEvents []*CustomEvent `protobuf:"bytes,4,rep,name=CustomEvents,proto3" json:"CustomEvents,omitempty"`
}

func (x *DexeEvents) Reset() {
	*x = DexeEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dexeEvents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DexeEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DexeEvents) ProtoMessage() {}

func (x *DexeEvents) ProtoReflect() protoreflect.Message {
	mi := &file_dexeEvents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DexeEvents.ProtoReflect.Descriptor instead.
func (*DexeEvents) Descriptor() ([]byte, []int) {
	return file_dexeEvents_proto_rawDescGZIP(), []int{0}
}

func (x *DexeEvents) GetNumber() []byte {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *DexeEvents) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DexeEvents) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DexeEvents) GetCustomEvents() []*CustomEvent {
	if x != nil {
		return x.CustomEvents
	}
	return nil
}

var File_dexeEvents_proto protoreflect.FileDescriptor

var file_dexeEvents_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x65, 0x78, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x1a, 0x11, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01,
	0x0a, 0x0a, 0x44, 0x65, 0x78, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x37, 0x0a, 0x0c,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x6b, 0x67, 0x2d, 0x62, 0x69,
	0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dexeEvents_proto_rawDescOnce sync.Once
	file_dexeEvents_proto_rawDescData = file_dexeEvents_proto_rawDesc
)

func file_dexeEvents_proto_rawDescGZIP() []byte {
	file_dexeEvents_proto_rawDescOnce.Do(func() {
		file_dexeEvents_proto_rawDescData = protoimpl.X.CompressGZIP(file_dexeEvents_proto_rawDescData)
	})
	return file_dexeEvents_proto_rawDescData
}

var file_dexeEvents_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dexeEvents_proto_goTypes = []interface{}{
	(*DexeEvents)(nil),  // 0: binary.DexeEvents
	(*CustomEvent)(nil), // 1: binary.CustomEvent
}
var file_dexeEvents_proto_depIdxs = []int32{
	1, // 0: binary.DexeEvents.CustomEvents:type_name -> binary.CustomEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dexeEvents_proto_init() }
func file_dexeEvents_proto_init() {
	if File_dexeEvents_proto != nil {
		return
	}
	file_customEvent_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dexeEvents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DexeEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dexeEvents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dexeEvents_proto_goTypes,
		DependencyIndexes: file_dexeEvents_proto_depIdxs,
		MessageInfos:      file_dexeEvents_proto_msgTypes,
	}.Build()
	File_dexeEvents_proto = out.File
	file_dexeEvents_proto_rawDesc = nil
	file_dexeEvents_proto_goTypes = nil
	file_dexeEvents_proto_depIdxs = nil
}
