// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: enum.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiquidityType int32

const (
	LiquidityType_UNDEFINED_LIQUIDITY_TYPE LiquidityType = 0
	LiquidityType_CEX                      LiquidityType = 1
	LiquidityType_DEX                      LiquidityType = 2
	LiquidityType_USER                     LiquidityType = 4
	LiquidityType_CUSTOM                   LiquidityType = 5
)

// Enum value maps for LiquidityType.
var (
	LiquidityType_name = map[int32]string{
		0: "UNDEFINED_LIQUIDITY_TYPE",
		1: "CEX",
		2: "DEX",
		4: "USER",
		5: "CUSTOM",
	}
	LiquidityType_value = map[string]int32{
		"UNDEFINED_LIQUIDITY_TYPE": 0,
		"CEX":                      1,
		"DEX":                      2,
		"USER":                     4,
		"CUSTOM":                   5,
	}
)

func (x LiquidityType) Enum() *LiquidityType {
	p := new(LiquidityType)
	*p = x
	return p
}

func (x LiquidityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiquidityType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (LiquidityType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x LiquidityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiquidityType.Descriptor instead.
func (LiquidityType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

type LiquiditySource int32

const (
	LiquiditySource_UNDEFINED_LIQUIDITY_SOURCE LiquiditySource = 0
	LiquiditySource_UNISWAP_V2                 LiquiditySource = 1
	LiquiditySource_UNISWAP_V3                 LiquiditySource = 2
	LiquiditySource_UNISWAP_V4                 LiquiditySource = 3
	LiquiditySource_BINANCE                    LiquiditySource = 5
	LiquiditySource_BYBIT                      LiquiditySource = 6
)

// Enum value maps for LiquiditySource.
var (
	LiquiditySource_name = map[int32]string{
		0: "UNDEFINED_LIQUIDITY_SOURCE",
		1: "UNISWAP_V2",
		2: "UNISWAP_V3",
		3: "UNISWAP_V4",
		5: "BINANCE",
		6: "BYBIT",
	}
	LiquiditySource_value = map[string]int32{
		"UNDEFINED_LIQUIDITY_SOURCE": 0,
		"UNISWAP_V2":                 1,
		"UNISWAP_V3":                 2,
		"UNISWAP_V4":                 3,
		"BINANCE":                    5,
		"BYBIT":                      6,
	}
)

func (x LiquiditySource) Enum() *LiquiditySource {
	p := new(LiquiditySource)
	*p = x
	return p
}

func (x LiquiditySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiquiditySource) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[1].Descriptor()
}

func (LiquiditySource) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[1]
}

func (x LiquiditySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiquiditySource.Descriptor instead.
func (LiquiditySource) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1}
}

type Direction int32

const (
	Direction_UNDEFINED_LIQUIDITY_DIRECTION Direction = 0
	Direction_ADD                           Direction = 1
	Direction_SUB                           Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "UNDEFINED_LIQUIDITY_DIRECTION",
		1: "ADD",
		2: "SUB",
	}
	Direction_value = map[string]int32{
		"UNDEFINED_LIQUIDITY_DIRECTION": 0,
		"ADD":                           1,
		"SUB":                           2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{2}
}

type Side int32

const (
	Side_UNDEFINED_LIQUIDITY_SIDE Side = 0
	Side_ASK                      Side = 1 // sell
	Side_BID                      Side = 2 // buy
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "UNDEFINED_LIQUIDITY_SIDE",
		1: "ASK",
		2: "BID",
	}
	Side_value = map[string]int32{
		"UNDEFINED_LIQUIDITY_SIDE": 0,
		"ASK":                      1,
		"BID":                      2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[3].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[3]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{3}
}

type WalletType int32

const (
	WalletType_UNDEFINED_TYPE WalletType = 0
	WalletType_SPOT           WalletType = 1
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "UNDEFINED_TYPE",
		1: "SPOT",
	}
	WalletType_value = map[string]int32{
		"UNDEFINED_TYPE": 0,
		"SPOT":           1,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[4].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[4]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{4}
}

type OrderType int32

const (
	OrderType_UNDEFINED_ORDER_TYPE OrderType = 0
	OrderType_MARKET               OrderType = 1
	OrderType_LIMIT                OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "UNDEFINED_ORDER_TYPE",
		1: "MARKET",
		2: "LIMIT",
	}
	OrderType_value = map[string]int32{
		"UNDEFINED_ORDER_TYPE": 0,
		"MARKET":               1,
		"LIMIT":                2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[5].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[5]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{5}
}

type TimeInForce int32

const (
	TimeInForce_UNDEFINED_TIME_IN_FORCE TimeInForce = 0
	TimeInForce_GTC                     TimeInForce = 1 // Good-Till-Cancel
	TimeInForce_IOC                     TimeInForce = 2 // Immediate-Or-Cancel
	TimeInForce_AON                     TimeInForce = 3 // All-Or-None
	TimeInForce_FOK                     TimeInForce = 4 // Fill-Or-Kill
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "UNDEFINED_TIME_IN_FORCE",
		1: "GTC",
		2: "IOC",
		3: "AON",
		4: "FOK",
	}
	TimeInForce_value = map[string]int32{
		"UNDEFINED_TIME_IN_FORCE": 0,
		"GTC":                     1,
		"IOC":                     2,
		"AON":                     3,
		"FOK":                     4,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[6].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[6]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{6}
}

type OrderStatus int32

const (
	OrderStatus_UNDEFINED_ORDER_STATUS OrderStatus = 0
	OrderStatus_PENDING                OrderStatus = 1
	OrderStatus_OPEN                   OrderStatus = 2
	OrderStatus_CANCELED               OrderStatus = 3
	OrderStatus_PARTIAL_CANCELED       OrderStatus = 4
	OrderStatus_PARTIAL_FILLED         OrderStatus = 5
	OrderStatus_FILLED                 OrderStatus = 6
	OrderStatus_EXPIRED                OrderStatus = 7
	OrderStatus_FAILED                 OrderStatus = 8
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNDEFINED_ORDER_STATUS",
		1: "PENDING",
		2: "OPEN",
		3: "CANCELED",
		4: "PARTIAL_CANCELED",
		5: "PARTIAL_FILLED",
		6: "FILLED",
		7: "EXPIRED",
		8: "FAILED",
	}
	OrderStatus_value = map[string]int32{
		"UNDEFINED_ORDER_STATUS": 0,
		"PENDING":                1,
		"OPEN":                   2,
		"CANCELED":               3,
		"PARTIAL_CANCELED":       4,
		"PARTIAL_FILLED":         5,
		"FILLED":                 6,
		"EXPIRED":                7,
		"FAILED":                 8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[7].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[7]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{7}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNDEFINED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_NEW       OperationStatus = 1
	OperationStatus_OPERATION_STATUS_PENDING   OperationStatus = 2
	OperationStatus_OPERATION_STATUS_COMPLETED OperationStatus = 3
	OperationStatus_OPERATION_STATUS_FAILED    OperationStatus = 4
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNDEFINED",
		1: "OPERATION_STATUS_NEW",
		2: "OPERATION_STATUS_PENDING",
		3: "OPERATION_STATUS_COMPLETED",
		4: "OPERATION_STATUS_FAILED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNDEFINED": 0,
		"OPERATION_STATUS_NEW":       1,
		"OPERATION_STATUS_PENDING":   2,
		"OPERATION_STATUS_COMPLETED": 3,
		"OPERATION_STATUS_FAILED":    4,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[8].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[8]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{8}
}

type Network int32

const (
	Network_NETWORK_UNDEFINED       Network = 0
	Network_NETWORK_BSC             Network = 1
	Network_NETWORK_ETH             Network = 2
	Network_NETWORK_POLYGON         Network = 3
	Network_NETWORK_BSC_TESTNET     Network = 4
	Network_NETWORK_ETH_TESTNET     Network = 5
	Network_NETWORK_POLYGON_TESTNET Network = 6
)

// Enum value maps for Network.
var (
	Network_name = map[int32]string{
		0: "NETWORK_UNDEFINED",
		1: "NETWORK_BSC",
		2: "NETWORK_ETH",
		3: "NETWORK_POLYGON",
		4: "NETWORK_BSC_TESTNET",
		5: "NETWORK_ETH_TESTNET",
		6: "NETWORK_POLYGON_TESTNET",
	}
	Network_value = map[string]int32{
		"NETWORK_UNDEFINED":       0,
		"NETWORK_BSC":             1,
		"NETWORK_ETH":             2,
		"NETWORK_POLYGON":         3,
		"NETWORK_BSC_TESTNET":     4,
		"NETWORK_ETH_TESTNET":     5,
		"NETWORK_POLYGON_TESTNET": 6,
	}
)

func (x Network) Enum() *Network {
	p := new(Network)
	*p = x
	return p
}

func (x Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[9].Descriptor()
}

func (Network) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[9]
}

func (x Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Network.Descriptor instead.
func (Network) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{9}
}

var File_enum_proto protoreflect.FileDescriptor

var file_enum_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0x55, 0x0a, 0x0d, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45,
	0x44, 0x5f, 0x4c, 0x49, 0x51, 0x55, 0x49, 0x44, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x45, 0x58, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x44,
	0x45, 0x58, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10, 0x05, 0x2a, 0x79, 0x0a, 0x0f, 0x4c, 0x69,
	0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a,
	0x1a, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x4c, 0x49, 0x51, 0x55, 0x49,
	0x44, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a,
	0x0a, 0x55, 0x4e, 0x49, 0x53, 0x57, 0x41, 0x50, 0x5f, 0x56, 0x32, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x55, 0x4e, 0x49, 0x53, 0x57, 0x41, 0x50, 0x5f, 0x56, 0x33, 0x10, 0x02, 0x12, 0x0e, 0x0a,
	0x0a, 0x55, 0x4e, 0x49, 0x53, 0x57, 0x41, 0x50, 0x5f, 0x56, 0x34, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x42, 0x49, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x59,
	0x42, 0x49, 0x54, 0x10, 0x06, 0x2a, 0x40, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x1d, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f,
	0x4c, 0x49, 0x51, 0x55, 0x49, 0x44, 0x49, 0x54, 0x59, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x02, 0x2a, 0x36, 0x0a, 0x04, 0x53, 0x69, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x18, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x4c, 0x49, 0x51,
	0x55, 0x49, 0x44, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x49, 0x44, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x53, 0x4b, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x49, 0x44, 0x10, 0x02, 0x2a,
	0x2a, 0x0a, 0x0a, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x0e, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x50, 0x4f, 0x54, 0x10, 0x01, 0x2a, 0x3c, 0x0a, 0x09, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x44, 0x45,
	0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x02, 0x2a, 0x4e, 0x0a, 0x0b, 0x54, 0x69, 0x6d,
	0x65, 0x49, 0x6e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x55, 0x4e, 0x44, 0x45,
	0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x46, 0x4f,
	0x52, 0x43, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x43, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x49, 0x4f, 0x43, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4f, 0x4e, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x46, 0x4f, 0x4b, 0x10, 0x04, 0x2a, 0x9d, 0x01, 0x0a, 0x0b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x16, 0x55, 0x4e, 0x44,
	0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41,
	0x52, 0x54, 0x49, 0x41, 0x4c, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x04,
	0x12, 0x12, 0x0a, 0x0e, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x5f, 0x46, 0x49, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x06,
	0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x07, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x08, 0x2a, 0xa6, 0x01, 0x0a, 0x0f, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a,
	0x1a, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x4e, 0x45, 0x57, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x50, 0x45, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x10, 0x04, 0x2a, 0xa6, 0x01, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x15,
	0x0a, 0x11, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49,
	0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b,
	0x5f, 0x42, 0x53, 0x43, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52,
	0x4b, 0x5f, 0x45, 0x54, 0x48, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x45, 0x54, 0x57, 0x4f,
	0x52, 0x4b, 0x5f, 0x50, 0x4f, 0x4c, 0x59, 0x47, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13,
	0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x42, 0x53, 0x43, 0x5f, 0x54, 0x45, 0x53, 0x54,
	0x4e, 0x45, 0x54, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b,
	0x5f, 0x45, 0x54, 0x48, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x4e, 0x45, 0x54, 0x10, 0x05, 0x12, 0x1b,
	0x0a, 0x17, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x50, 0x4f, 0x4c, 0x59, 0x47, 0x4f,
	0x4e, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x4e, 0x45, 0x54, 0x10, 0x06, 0x42, 0x0b, 0x5a, 0x09, 0x70,
	0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData = file_enum_proto_rawDesc
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_proto_rawDescData)
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_enum_proto_goTypes = []interface{}{
	(LiquidityType)(0),   // 0: proto.LiquidityType
	(LiquiditySource)(0), // 1: proto.LiquiditySource
	(Direction)(0),       // 2: proto.Direction
	(Side)(0),            // 3: proto.Side
	(WalletType)(0),      // 4: proto.WalletType
	(OrderType)(0),       // 5: proto.OrderType
	(TimeInForce)(0),     // 6: proto.TimeInForce
	(OrderStatus)(0),     // 7: proto.OrderStatus
	(OperationStatus)(0), // 8: proto.OperationStatus
	(Network)(0),         // 9: proto.Network
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_rawDesc = nil
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
