// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: holder.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Holder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	From   string `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To     string `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Tx     string `protobuf:"bytes,4,opt,name=Tx,proto3" json:"Tx,omitempty"`
	Amount int64  `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *Holder) Reset() {
	*x = Holder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_holder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Holder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holder) ProtoMessage() {}

func (x *Holder) ProtoReflect() protoreflect.Message {
	mi := &file_holder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holder.ProtoReflect.Descriptor instead.
func (*Holder) Descriptor() ([]byte, []int) {
	return file_holder_proto_rawDescGZIP(), []int{0}
}

func (x *Holder) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Holder) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Holder) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Holder) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *Holder) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_holder_proto protoreflect.FileDescriptor

var file_holder_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x6a, 0x0a, 0x06, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x6b, 0x67, 0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_holder_proto_rawDescOnce sync.Once
	file_holder_proto_rawDescData = file_holder_proto_rawDesc
)

func file_holder_proto_rawDescGZIP() []byte {
	file_holder_proto_rawDescOnce.Do(func() {
		file_holder_proto_rawDescData = protoimpl.X.CompressGZIP(file_holder_proto_rawDescData)
	})
	return file_holder_proto_rawDescData
}

var file_holder_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_holder_proto_goTypes = []interface{}{
	(*Holder)(nil), // 0: binary.Holder
}
var file_holder_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_holder_proto_init() }
func file_holder_proto_init() {
	if File_holder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_holder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Holder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_holder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_holder_proto_goTypes,
		DependencyIndexes: file_holder_proto_depIdxs,
		MessageInfos:      file_holder_proto_msgTypes,
	}.Build()
	File_holder_proto = out.File
	file_holder_proto_rawDesc = nil
	file_holder_proto_goTypes = nil
	file_holder_proto_depIdxs = nil
}
