// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: limitTrade.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LimitTrade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            uint32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OrderId       uint32  `protobuf:"varint,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Status        string  `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	AmountIn      string  `protobuf:"bytes,4,opt,name=AmountIn,proto3" json:"AmountIn,omitempty"`
	AmountOut     string  `protobuf:"bytes,5,opt,name=AmountOut,proto3" json:"AmountOut,omitempty"`
	GasPrice      int64   `protobuf:"varint,6,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	GasValue      int64   `protobuf:"varint,7,opt,name=GasValue,proto3" json:"GasValue,omitempty"`
	TriggerTx     string  `protobuf:"bytes,8,opt,name=TriggerTx,proto3" json:"TriggerTx,omitempty"`
	ExecutionTx   string  `protobuf:"bytes,9,opt,name=ExecutionTx,proto3" json:"ExecutionTx,omitempty"`
	FailureReason string  `protobuf:"bytes,10,opt,name=FailureReason,proto3" json:"FailureReason,omitempty"`
	Price         float64 `protobuf:"fixed64,11,opt,name=Price,proto3" json:"Price,omitempty"`
	PriceUSD      float64 `protobuf:"fixed64,12,opt,name=PriceUSD,proto3" json:"PriceUSD,omitempty"`
}

func (x *LimitTrade) Reset() {
	*x = LimitTrade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_limitTrade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitTrade) ProtoMessage() {}

func (x *LimitTrade) ProtoReflect() protoreflect.Message {
	mi := &file_limitTrade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitTrade.ProtoReflect.Descriptor instead.
func (*LimitTrade) Descriptor() ([]byte, []int) {
	return file_limitTrade_proto_rawDescGZIP(), []int{0}
}

func (x *LimitTrade) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *LimitTrade) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *LimitTrade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LimitTrade) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *LimitTrade) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *LimitTrade) GetGasPrice() int64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *LimitTrade) GetGasValue() int64 {
	if x != nil {
		return x.GasValue
	}
	return 0
}

func (x *LimitTrade) GetTriggerTx() string {
	if x != nil {
		return x.TriggerTx
	}
	return ""
}

func (x *LimitTrade) GetExecutionTx() string {
	if x != nil {
		return x.ExecutionTx
	}
	return ""
}

func (x *LimitTrade) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *LimitTrade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *LimitTrade) GetPriceUSD() float64 {
	if x != nil {
		return x.PriceUSD
	}
	return 0
}

var File_limitTrade_proto protoreflect.FileDescriptor

var file_limitTrade_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0xd8, 0x02, 0x0a, 0x0a, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x4f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x47, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x78, 0x12, 0x24, 0x0a,
	0x0d, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x55, 0x53, 0x44, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x55, 0x53, 0x44, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x6b, 0x67, 0x2d, 0x62, 0x69,
	0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_limitTrade_proto_rawDescOnce sync.Once
	file_limitTrade_proto_rawDescData = file_limitTrade_proto_rawDesc
)

func file_limitTrade_proto_rawDescGZIP() []byte {
	file_limitTrade_proto_rawDescOnce.Do(func() {
		file_limitTrade_proto_rawDescData = protoimpl.X.CompressGZIP(file_limitTrade_proto_rawDescData)
	})
	return file_limitTrade_proto_rawDescData
}

var file_limitTrade_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_limitTrade_proto_goTypes = []interface{}{
	(*LimitTrade)(nil), // 0: binary.LimitTrade
}
var file_limitTrade_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_limitTrade_proto_init() }
func file_limitTrade_proto_init() {
	if File_limitTrade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_limitTrade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitTrade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_limitTrade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_limitTrade_proto_goTypes,
		DependencyIndexes: file_limitTrade_proto_depIdxs,
		MessageInfos:      file_limitTrade_proto_msgTypes,
	}.Build()
	File_limitTrade_proto = out.File
	file_limitTrade_proto_rawDesc = nil
	file_limitTrade_proto_goTypes = nil
	file_limitTrade_proto_depIdxs = nil
}
