// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: priceUpdates.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceHolder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair      string `protobuf:"bytes,1,opt,name=Pair,proto3" json:"Pair,omitempty"`
	Chain     string `protobuf:"bytes,2,opt,name=Chain,proto3" json:"Chain,omitempty"`
	PriceA    string `protobuf:"bytes,3,opt,name=PriceA,proto3" json:"PriceA,omitempty"`
	PriceAUSD string `protobuf:"bytes,4,opt,name=PriceAUSD,proto3" json:"PriceAUSD,omitempty"`
	PriceB    string `protobuf:"bytes,5,opt,name=PriceB,proto3" json:"PriceB,omitempty"`
	PriceBUSD string `protobuf:"bytes,6,opt,name=PriceBUSD,proto3" json:"PriceBUSD,omitempty"`
}

func (x *PriceHolder) Reset() {
	*x = PriceHolder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_priceUpdates_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHolder) ProtoMessage() {}

func (x *PriceHolder) ProtoReflect() protoreflect.Message {
	mi := &file_priceUpdates_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHolder.ProtoReflect.Descriptor instead.
func (*PriceHolder) Descriptor() ([]byte, []int) {
	return file_priceUpdates_proto_rawDescGZIP(), []int{0}
}

func (x *PriceHolder) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *PriceHolder) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *PriceHolder) GetPriceA() string {
	if x != nil {
		return x.PriceA
	}
	return ""
}

func (x *PriceHolder) GetPriceAUSD() string {
	if x != nil {
		return x.PriceAUSD
	}
	return ""
}

func (x *PriceHolder) GetPriceB() string {
	if x != nil {
		return x.PriceB
	}
	return ""
}

func (x *PriceHolder) GetPriceBUSD() string {
	if x != nil {
		return x.PriceBUSD
	}
	return ""
}

type PriceUpdates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*PriceHolder `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *PriceUpdates) Reset() {
	*x = PriceUpdates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_priceUpdates_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdates) ProtoMessage() {}

func (x *PriceUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_priceUpdates_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdates.ProtoReflect.Descriptor instead.
func (*PriceUpdates) Descriptor() ([]byte, []int) {
	return file_priceUpdates_proto_rawDescGZIP(), []int{1}
}

func (x *PriceUpdates) GetItems() []*PriceHolder {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_priceUpdates_proto protoreflect.FileDescriptor

var file_priceUpdates_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0xa3, 0x01, 0x0a,
	0x0b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x69, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x55, 0x53, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x55, 0x53, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x42, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x55, 0x53,
	0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x55,
	0x53, 0x44, 0x22, 0x39, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x12, 0x5a,
	0x10, 0x2f, 0x70, 0x6b, 0x67, 0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_priceUpdates_proto_rawDescOnce sync.Once
	file_priceUpdates_proto_rawDescData = file_priceUpdates_proto_rawDesc
)

func file_priceUpdates_proto_rawDescGZIP() []byte {
	file_priceUpdates_proto_rawDescOnce.Do(func() {
		file_priceUpdates_proto_rawDescData = protoimpl.X.CompressGZIP(file_priceUpdates_proto_rawDescData)
	})
	return file_priceUpdates_proto_rawDescData
}

var file_priceUpdates_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_priceUpdates_proto_goTypes = []interface{}{
	(*PriceHolder)(nil),  // 0: binary.PriceHolder
	(*PriceUpdates)(nil), // 1: binary.PriceUpdates
}
var file_priceUpdates_proto_depIdxs = []int32{
	0, // 0: binary.PriceUpdates.Items:type_name -> binary.PriceHolder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_priceUpdates_proto_init() }
func file_priceUpdates_proto_init() {
	if File_priceUpdates_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_priceUpdates_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceHolder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_priceUpdates_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceUpdates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_priceUpdates_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_priceUpdates_proto_goTypes,
		DependencyIndexes: file_priceUpdates_proto_depIdxs,
		MessageInfos:      file_priceUpdates_proto_msgTypes,
	}.Build()
	File_priceUpdates_proto = out.File
	file_priceUpdates_proto_rawDesc = nil
	file_priceUpdates_proto_goTypes = nil
	file_priceUpdates_proto_depIdxs = nil
}
