// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: trade.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair      string  `protobuf:"bytes,1,opt,name=Pair,proto3" json:"Pair,omitempty"`
	PriceA    float64 `protobuf:"fixed64,2,opt,name=PriceA,proto3" json:"PriceA,omitempty"`
	PriceB    float64 `protobuf:"fixed64,3,opt,name=PriceB,proto3" json:"PriceB,omitempty"`
	PriceAUSD float64 `protobuf:"fixed64,4,opt,name=PriceAUSD,proto3" json:"PriceAUSD,omitempty"`
	PriceBUSD float64 `protobuf:"fixed64,5,opt,name=PriceBUSD,proto3" json:"PriceBUSD,omitempty"`
	VolumeA   []byte  `protobuf:"bytes,6,opt,name=VolumeA,proto3" json:"VolumeA,omitempty"`
	VolumeB   []byte  `protobuf:"bytes,7,opt,name=VolumeB,proto3" json:"VolumeB,omitempty"`
	VolumeUSD float64 `protobuf:"fixed64,8,opt,name=VolumeUSD,proto3" json:"VolumeUSD,omitempty"`
	IsBuy     bool    `protobuf:"varint,9,opt,name=IsBuy,proto3" json:"IsBuy,omitempty"`
}

func (x *Trade) Reset() {
	*x = Trade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Trade) GetPriceA() float64 {
	if x != nil {
		return x.PriceA
	}
	return 0
}

func (x *Trade) GetPriceB() float64 {
	if x != nil {
		return x.PriceB
	}
	return 0
}

func (x *Trade) GetPriceAUSD() float64 {
	if x != nil {
		return x.PriceAUSD
	}
	return 0
}

func (x *Trade) GetPriceBUSD() float64 {
	if x != nil {
		return x.PriceBUSD
	}
	return 0
}

func (x *Trade) GetVolumeA() []byte {
	if x != nil {
		return x.VolumeA
	}
	return nil
}

func (x *Trade) GetVolumeB() []byte {
	if x != nil {
		return x.VolumeB
	}
	return nil
}

func (x *Trade) GetVolumeUSD() float64 {
	if x != nil {
		return x.VolumeUSD
	}
	return 0
}

func (x *Trade) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

var File_trade_proto protoreflect.FileDescriptor

var file_trade_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0xef, 0x01, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x61, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x42, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x42, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x55, 0x53, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x55, 0x53,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x55, 0x53, 0x44, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x55, 0x53, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x41, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x41, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x42, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x42, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x55, 0x53, 0x44,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x55, 0x53,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x42, 0x75, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x49, 0x73, 0x42, 0x75, 0x79, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x6b, 0x67, 0x2d,
	0x62, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_trade_proto_rawDescOnce sync.Once
	file_trade_proto_rawDescData = file_trade_proto_rawDesc
)

func file_trade_proto_rawDescGZIP() []byte {
	file_trade_proto_rawDescOnce.Do(func() {
		file_trade_proto_rawDescData = protoimpl.X.CompressGZIP(file_trade_proto_rawDescData)
	})
	return file_trade_proto_rawDescData
}

var file_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trade_proto_goTypes = []interface{}{
	(*Trade)(nil), // 0: binary.Trade
}
var file_trade_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trade_proto_init() }
func file_trade_proto_init() {
	if File_trade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_proto_goTypes,
		DependencyIndexes: file_trade_proto_depIdxs,
		MessageInfos:      file_trade_proto_msgTypes,
	}.Build()
	File_trade_proto = out.File
	file_trade_proto_rawDesc = nil
	file_trade_proto_goTypes = nil
	file_trade_proto_depIdxs = nil
}
