// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: transferEvent.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain       string `protobuf:"bytes,1,opt,name=Chain,proto3" json:"Chain,omitempty"`
	Contract    string `protobuf:"bytes,2,opt,name=Contract,proto3" json:"Contract,omitempty"`
	BlockNumber uint64 `protobuf:"varint,3,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	Date        int64  `protobuf:"varint,4,opt,name=Date,proto3" json:"Date,omitempty"`
	Order       uint32 `protobuf:"varint,5,opt,name=Order,proto3" json:"Order,omitempty"`
	Tx          string `protobuf:"bytes,6,opt,name=Tx,proto3" json:"Tx,omitempty"`
	From        string `protobuf:"bytes,7,opt,name=From,proto3" json:"From,omitempty"`
	To          string `protobuf:"bytes,8,opt,name=To,proto3" json:"To,omitempty"`
	Amount      string `protobuf:"bytes,9,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ValueUSD    string `protobuf:"bytes,10,opt,name=ValueUSD,proto3" json:"ValueUSD,omitempty"`
}

func (x *TransferEvent) Reset() {
	*x = TransferEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transferEvent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEvent) ProtoMessage() {}

func (x *TransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_transferEvent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEvent.ProtoReflect.Descriptor instead.
func (*TransferEvent) Descriptor() ([]byte, []int) {
	return file_transferEvent_proto_rawDescGZIP(), []int{0}
}

func (x *TransferEvent) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TransferEvent) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *TransferEvent) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TransferEvent) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *TransferEvent) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TransferEvent) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *TransferEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferEvent) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferEvent) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferEvent) GetValueUSD() string {
	if x != nil {
		return x.ValueUSD
	}
	return ""
}

var File_transferEvent_proto protoreflect.FileDescriptor

var file_transferEvent_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0xf5, 0x01,
	0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x54, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x55, 0x53, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x55, 0x53, 0x44, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x6b, 0x67, 0x2d, 0x62, 0x69,
	0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_transferEvent_proto_rawDescOnce sync.Once
	file_transferEvent_proto_rawDescData = file_transferEvent_proto_rawDesc
)

func file_transferEvent_proto_rawDescGZIP() []byte {
	file_transferEvent_proto_rawDescOnce.Do(func() {
		file_transferEvent_proto_rawDescData = protoimpl.X.CompressGZIP(file_transferEvent_proto_rawDescData)
	})
	return file_transferEvent_proto_rawDescData
}

var file_transferEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transferEvent_proto_goTypes = []interface{}{
	(*TransferEvent)(nil), // 0: binary.TransferEvent
}
var file_transferEvent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transferEvent_proto_init() }
func file_transferEvent_proto_init() {
	if File_transferEvent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transferEvent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transferEvent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transferEvent_proto_goTypes,
		DependencyIndexes: file_transferEvent_proto_depIdxs,
		MessageInfos:      file_transferEvent_proto_msgTypes,
	}.Build()
	File_transferEvent_proto = out.File
	file_transferEvent_proto_rawDesc = nil
	file_transferEvent_proto_goTypes = nil
	file_transferEvent_proto_depIdxs = nil
}
